apiVersion: eksctl.io/v1alpha5 
kind: ClusterConfig 
metadata: 
  name: martianbank-cluster 
  region: eu-central-1 
vpc: 
  cidr: "172.20.0.0/16" 
  nat: 
   gateway: Single 
  clusterEndpoints: 
   publicAccess: true 
   privateAccess: false 
nodeGroups: 
  - name: ng-1 
    minSize: 1 
    maxSize: 1 
    desiredCapacity: 1
    instancesDistribution: 
      maxPrice: 0.050 
      instanceTypes: ["t3a.medium", "t3.medium", "t4g.medium"] 
      onDemandBaseCapacity: 0 
      onDemandPercentageAboveBaseCapacity: 20 
      spotInstancePools: 3 
    ssh: 
     publicKeyPath: <PUBLIC_KEY_PATH>