apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-martianbank
data:
    DB_URL: "<DB_CONNECTION_STRING>"
    JWT_SECRET: "anyjwt"
    ACCOUNTS_SERVICE_URL: "http://accounts:50051"
# Set any string as a JWT_SECRET for generating and verifying JWT tokens.